# Generated by Django 5.0.4 on 2024-04-23 13:48

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_myrefreshtoken_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrefreshtoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 13, 48, 22, 491822), verbose_name='expired time'),
        ),
        migrations.AlterField(
            model_name='myrefreshtoken',
            name='value',
            field=models.UUIDField(default=uuid.UUID('eed59ec7-99b4-4c79-9128-592737a1bc9c')),
        ),
    ]
